### ISSUE TITLE
Milestones para Versão 1.0

### ISSUE THREAD

**Issue by andreidl** [raijenki/elysium#1]
Versão 1.0:
  -  [x]  Tradução dos Arquivos
  -  [x]  Refazer design / layout
  -  [x]  Serialização das operações
  -  [x]  Adicionar algumas coisas por padrão (imagens, áudios, etc)
